name: Publish Conda Package

on: [push]

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: myenv

      - name: Install dependencies
        shell: pwsh
        run: |
          conda install conda-build anaconda-client

      - name: Build Conda package
        shell: pwsh
        run: |
          conda build . -c conda-forge -c alexsk -c cfobel -c conda-forge -c dropbot

      - name: Upload Conda package
        shell: pwsh
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          $output = conda build . --output
          anaconda upload --user vignesh229 --token $env:ANACONDA_API_TOKEN $output
